version: '2'

services:
  web:
    env_file: .env
    image: datacite/levriero
    ports:
      - "8065:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
    networks:
      - public
  memcached:
    image: memcached:1.4.31
    networks:
      - public
  # db:
  #   environment:
  #     MYSQL_DATABASE: datacite
  #     MYSQL_USER: root
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #   image: mysql:5.6
  #   ports:
  #     - "3309:3306"
  #   networks:
  #     - public
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - public
  handle:
    env_file: .env
    image: osul/handle
    ports:
      - "2641:2641"
      - "8005:8000"
    networks:
      - public
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - public
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.40.0/24
        gateway: 10.0.40.1
