version: '2.1'

services:
  web:
    env_file: .env
    environment:
      - LOG_LEVEL=info
      - ELASTIC_PASSWORD=changeme
    image: datacite/levriero
    ports:
      - "8040:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./spec:/home/app/webapp/spec
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - public
  memcached:
    image: memcached:1.4.31
    networks:
      - public
  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - public
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
    networks:
      - public
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:9200
      interval: 10s
      timeout: 1s
  elasticsearch-test:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    ports:
      - "9250:9200"
      - "9350:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
    networks:
      - public
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.70.0/24
        gateway: 10.0.70.1
