version: '2.1'

services:
  web:
    env_file: .env
    environment:
      - LOG_LEVEL=info
    image: datacite/levriero
    build: .
    ports:
      - "8045:80"
      - "2245:22"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
    depends_on:
      - localstack

  memcached:
    image: memcached:1.6.32

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
