version: '2.1'

services:
  web:
    env_file: .env
    environment:
      - LOG_LEVEL=info
      - LAGOTTINO_URL=https://api.stage.datacite.org
    image: datacite/levriero
    build: .
    ports:
      - "8045:80"
      - "2245:22"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
    networks:
      - public
  memcached:
    image: memcached:1.4.31
    networks:
      - public
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.70.0/24
          gateway: 10.0.70.1
