services:
  web:
    container_name: levriero_web
    platform: linux/amd64
    env_file: .env
    environment:
      - LOG_LEVEL=info
      - AWS_ENDPOINT=http://localstack:4566
      # - LAGOTTINO_URL=http://lupo_web # use this to to connect to localstack network
      - LAGOTTINO_URL=https://api.stage.datacite.org # use this value to run specs locally
    image: datacite/levriero
    ports:
      - "8045:80"
      - "2245:22"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
    dns:
      - 10.0.2.20
    networks:
      - localstack_network

  memcached:
    image: memcached:1.6.32
    container_name: levriero_memcached
    networks:
      - localstack_network

networks:
  localstack_network:
    external: true
