concurrency: 50
delay: 0
pidfile: tmp/pids/shoryuken.pid
queues:
  - doi
  - levriero

groups:
  levriero_usage:
    concurrency: 10
    queues:
      - levriero_usage
  usage:
    concurrency: 4
    queues:
      - usage
      # - levriero_usage
