name: Deploy
on:
  push:
    branches:
      - "master"
jobs:
  test:
    uses: ./.github/workflows/parallel_ci.yml
    secrets: inherit

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: [test, build]
    uses: ./.github/workflows/update_terraform.yml
    secrets: inherit
