name: Update Terraform
on:
  workflow_call:
jobs:
  update-terraform:
    runs-on: ubuntu-latest
    env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Extract variables
          shell: bash
          run: |
            echo "::set-output name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
            echo "::set-output name=TAG::$(git tag --points-at HEAD)"
            echo "::set-output name=GIT_SHA::$(git rev-parse HEAD)"
            echo "::set-output name=GIT_SHA_SHORT::$(git rev-parse --short HEAD)"
            echo "::set-output name=MESSAGE::$(git log --format=%B -n 1 ${{ github.event.after }})"
          id: extract_variables

        - name: Checkout terraform config repo
          uses: actions/checkout@v2
          with:
            # public repo with terraform configuration
            repository: "datacite/mastino"
            persist-credentials: false
        - name: Commit changes to terraform config repository
          # use go template in terraform config repository to update git sha and tag
          # commit and push changes to trigger terraform workflow
          run: |
            export GIT_SHA=${{ steps.extract_variables.outputs.GIT_SHA_SHORT }}
            export GIT_TAG=${{ steps.extract_variables.outputs.TAG }}

            export VERSION_FILENAME=stage/services/levriero/_levriero.auto.tfvars

            sed -e "s/{{ .Env.GIT_SHA }}/$GIT_SHA/g" -e "s/{{ .Env.GIT_TAG }}/$GIT_TAG/g" $VERSION_FILENAME.tmpl > $VERSION_FILENAME

            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add $VERSION_FILENAME
            git commit -m "Adding levriero git variables for commit ${{ steps.extract_variables.outputs.GIT_SHA }}"
        - name: Push changes
          uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            repository: "datacite/mastino"
            branch: "refs/heads/master"
            tags: false
